### ISSUE TITLE
Handle special commands

### ISSUE THREAD

**Issue by eladrave** [eladrave/WhatsappOAIAssistant#7]
Once you receive the body of the message, and before sending to the assistant see is there is a special command:

`/clear` - this creates a new thread - responds - "clear"
`/remember` - takes the text after that (like /remember I have a meeting tomorrow) - 
Send that to openai with a prompt "some prompt I will design later" , takes the result, saves it in a temp .txt file, uploads it to the file storage, and add that file ID to the vector store

(This means we need to add "vectorstoreid" to the enviroment)

**Comment by TalalZoabi** [comment]
We need a module to handle that

**Comment by TalalZoabi** [comment]
SpecialCommand module manages and executes the commands

**Comment by TalalZoabi** [comment]
added /reset command that deletes the user's current session (allows for better debugging of long term memory)

**Comment by TalalZoabi** [comment]
adeded support for creation of commands
